/**
 * Pin the Apple development team on the generated Xcode project.
 *
 * AUTHORSHIP: Claude. Build configuration.
 *
 * `ios/` is regenerated by `expo prebuild`, so setting the team in Xcode by
 * hand does not survive. This sets it every time the project is generated.
 *
 * The team is the PAID one. Signing with the free personal team was the cause
 * of an evening lost to `ppq.apple.com` refusing to verify the app — free
 * accounts go through Apple's anti-piracy check on every install, paid accounts
 * do not. See NOTES.md 2026-08-20.
 */

const { withXcodeProject } = require('@expo/config-plugins');

const DEVELOPMENT_TEAM = 'A4367BS428';

module.exports = function withDevelopmentTeam(config) {
  return withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      if (typeof entry !== 'object' || !entry.buildSettings) continue;
      // Only the app target: the Pods targets neither need nor want a team.
      if (entry.buildSettings.PRODUCT_BUNDLE_IDENTIFIER === undefined) continue;
      entry.buildSettings.DEVELOPMENT_TEAM = DEVELOPMENT_TEAM;
      entry.buildSettings.CODE_SIGN_STYLE = 'Automatic';
    }
    return mod;
  });
};
