/**
 * The form check, end to end, on photographs of a filled-in form.
 *
 * AUTHORSHIP: Claude. Tests for src/lib/formcheck/.
 *
 * The fixtures are generated by `tools/forms/make-demo-sar7.py` and read by the
 * same Apple Vision build the corpus uses (`tools/forms/build-demo-sar7.sh`):
 * one scan-flat page, five simulated phone photos with perspective, uneven light
 * and blur, and one photograph of a DIFFERENT SAR 7 layout, which must be
 * refused rather than judged. `specs.json` says what was drawn on each; this
 * file checks the engine reports exactly that.
 *
 * These are synthetic photographs of a fictional form. They prove the geometry
 * and the ink measurement agree with what was drawn; they are not a claim about
 * accuracy on real phones, which has not been measured.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import jpeg from 'jpeg-js';

import { checkFilledForm, checkedCount, carriesMarker } from '../../src/lib/formcheck/check.ts';
import type { Finding, FormCheck } from '../../src/lib/formcheck/check.ts';
import { fitHomography, applyHomography, ransacHomography } from '../../src/lib/formcheck/homography.ts';
import type { Point } from '../../src/lib/formcheck/homography.ts';
import { toGray } from '../../src/lib/formcheck/ink.ts';
import { parseFormTemplate, sameFormId } from '../../src/lib/formcheck/template.ts';
import { compareDates, lastDayOf, parseReportMonth, parseWrittenDate } from '../../src/lib/formcheck/written-date.ts';
import type { OcrLine } from '../../src/lib/ocr/types.ts';
import { REPO_ROOT } from '../../tools/metrics/corpus.ts';

const FIXTURES = join(REPO_ROOT, 'tests/fixtures/formcheck');
const template = parseFormTemplate(JSON.parse(readFileSync(join(REPO_ROOT, 'content/forms/carta-demo-sar7.json'), 'utf8')));

interface Spec {
  readonly name: string;
  readonly answers: Readonly<Record<string, 'yes' | 'no' | 'both' | null>>;
  readonly signed: boolean;
  readonly date: string | null;
}
const specs = JSON.parse(readFileSync(join(FIXTURES, 'specs.json'), 'utf8')) as Spec[];

function load(name: string): { lines: OcrLine[]; ocrWidth: number; ocrHeight: number; image: ReturnType<typeof toGray> } {
  const ocr = JSON.parse(readFileSync(join(FIXTURES, `${name}.ocr.json`), 'utf8').split('\n')[0] ?? '{}') as {
    lines: OcrLine[];
    ocrWidth: number;
    ocrHeight: number;
  };
  const raw = jpeg.decode(readFileSync(join(FIXTURES, `${name}.jpg`)), { useTArray: true, formatAsRGBA: true });
  return { lines: ocr.lines, ocrWidth: ocr.ocrWidth, ocrHeight: ocr.ocrHeight, image: toGray(raw.data, raw.width, raw.height) };
}

const results = new Map<string, FormCheck>();
function check(name: string): FormCheck {
  const hit = results.get(name);
  if (hit) return hit;
  const result = checkFilledForm({ template, ...load(name) });
  results.set(name, result);
  return result;
}

function findings(name: string): readonly Finding[] {
  const result = check(name);
  if (!result.ok) throw new Error(`${name}: not checked (${result.reason})`);
  return result.findings;
}

const questionWhy = (answer: Spec['answers'][string] | undefined): string =>
  answer === null || answer === undefined ? 'no_box' : answer === 'both' ? 'both_boxes' : 'one_box';

describe('the form check reads each fixture as it was drawn', () => {
  for (const spec of specs) {
    describe(spec.name, () => {
      it('lines the photo up with the blank form', () => {
        expect(check(spec.name).ok).toBe(true);
      });

      it('finds every YES/NO question and reads the box that was marked', () => {
        const questions = findings(spec.name).filter((f) => f.kind === 'question');
        expect(questions).toHaveLength(template.questions.length);
        for (const q of questions) {
          if (q.kind !== 'question') continue;
          const drawn = spec.answers[`q${q.number}`];
          expect(q.why).toBe(questionWhy(drawn));
          expect(q.state).toBe(q.why === 'one_box' ? 'looks_done' : 'look_again');
          if (drawn === 'yes' || drawn === 'no') expect(q.answer).toBe(drawn);
        }
      });

      it('sees a signature exactly when one was drawn', () => {
        const signature = findings(spec.name).find((f) => f.kind === 'signature');
        expect(signature?.why).toBe(spec.signed ? 'signed' : 'no_signature');
      });

      it('reads the written date and compares it with the end of the report month', () => {
        const date = findings(spec.name).find((f) => f.kind === 'date');
        if (date?.kind !== 'date') throw new Error('no date finding');
        if (spec.date === null) {
          expect(date.why).toBe('not_dated');
          return;
        }
        const drawn = parseWrittenDate(spec.date);
        expect(date.written).toEqual(drawn);
        // The demo form's report month is AUGUST 2026, so anything dated
        // September or later is after it and August 28 is not.
        expect(date.reportMonthEnds).toEqual({ year: 2026, month: 8, day: 31 });
        expect(date.why).toBe(compareDates(drawn!, { year: 2026, month: 8, day: 31 }) > 0 ? 'after_report_month' : 'too_early');
      });
    });
  }
});

describe('what the check refuses to do', () => {
  it('refuses a different form instead of judging boxes that are not on it', () => {
    // A photograph of the corpus SAR 7, a different layout that shares most of
    // its words. Before the footer gate and the stricter label match, question 3
    // was judged against "Did your address change? NO" on this page.
    const result = check('other-layout');
    expect(result).toEqual({ ok: false, reason: 'different_form' });
  });

  it('refuses a page with too little text to line up', () => {
    const { image } = load('good-flat');
    const result = checkFilledForm({ template, lines: [], ocrWidth: 1700, ocrHeight: 2200, image });
    expect(result.ok).toBe(false);
  });

  it('counts only what it actually checked', () => {
    // Three questions, a signature and a date on every fixture it can line up.
    expect(checkedCount(findings('good-photo'))).toBe(5);
    expect(checkedCount(findings('blank-photo'))).toBe(5);
  });

  it('takes the date from the person when the recogniser could not read it', () => {
    const early = checkFilledForm({ template, ...load('good-photo'), writtenDate: { year: 2026, month: 8, day: 15 } });
    if (!early.ok) throw new Error('not checked');
    const date = early.findings.find((f) => f.kind === 'date');
    expect(date?.why).toBe('too_early');
  });

  it('never says "complete" in either language: it reports what it saw, the county decides', () => {
    for (const locale of ['en', 'es'] as const) {
      const strings = JSON.parse(readFileSync(join(REPO_ROOT, `src/lib/i18n/locales/${locale}.json`), 'utf8')) as {
        formcheck: Record<string, string>;
      };
      for (const [key, text] of Object.entries(strings.formcheck)) {
        expect(`${locale}.${key}: ${/\bcomplet[eoa]s?\b/i.test(text) ? text : 'ok'}`).toBe(`${locale}.${key}: ok`);
      }
    }
  });
});

describe('the template', () => {
  it('parses, and names the form it checks', () => {
    expect(template.formId).toBe('SAR 7');
    expect(template.questions.length).toBe(3);
    expect(template.anchors.length).toBeGreaterThanOrEqual(20);
  });

  it('quotes the real form for every rule it applies, with a source and a date', () => {
    for (const rule of Object.values(template.rules)) {
      expect(rule.formSays.length).toBeGreaterThan(10);
      expect(rule.ifNot.length).toBeGreaterThan(10);
    }
    expect(template.sourceUrl.startsWith('https://')).toBe(true);
    expect(template.verifiedOn).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it('rejects a template with a missing piece rather than checking half a form', () => {
    const raw = JSON.parse(readFileSync(join(REPO_ROOT, 'content/forms/carta-demo-sar7.json'), 'utf8')) as Record<string, unknown>;
    delete raw['footer_marker'];
    expect(() => parseFormTemplate(raw)).toThrow();
  });

  it('matches a form id however the letter prints it', () => {
    expect(sameFormId('SAR 7', 'SAR 7')).toBe(true);
    expect(sameFormId('SAR7 (Rev. 5/25)', 'SAR 7')).toBe(true);
    expect(sameFormId('sar-7', 'SAR 7')).toBe(true);
    expect(sameFormId('SAR 7A', 'SAR 7')).toBe(false);
    expect(sameFormId(undefined, 'SAR 7')).toBe(false);
  });

  it('only trusts a page that carries the demo footer', () => {
    const line = (text: string): OcrLine => ({ text, confidence: 1, box: { x: 0, y: 0.95, w: 0.5, h: 0.01 } });
    expect(carriesMarker([line('SAR 7 (Rev. 5/25) CARTA DEMONSTRATION COPY - NOT AN OFFICIAL FORM')], template.footerMarker)).toBe(true);
    expect(carriesMarker([line('SAR 7 (12/14)')], template.footerMarker)).toBe(false);
  });
});

describe('reading a handwritten date', () => {
  it.each([
    ['9/2/2026', { year: 2026, month: 9, day: 2 }],
    ['09-02-26', { year: 2026, month: 9, day: 2 }],
    ['9.2.26', { year: 2026, month: 9, day: 2 }],
    ['Sept 2, 2026', { year: 2026, month: 9, day: 2 }],
    ['2 de septiembre de 2026', { year: 2026, month: 9, day: 2 }],
    // The recogniser's usual confusions, repaired inside a number only.
    ['9/l/2O26', { year: 2026, month: 9, day: 1 }],
  ])('reads %s', (text, expected) => {
    expect(parseWrittenDate(text)).toEqual(expected);
  });

  it.each(['', 'Signature', '13/45/2026', '2/30/2026', 'Sept 2'])('refuses %p', (text) => {
    expect(parseWrittenDate(text)).toBeUndefined();
  });

  it('reads the report month after its label', () => {
    expect(parseReportMonth('SAR 7  Report Month: AUGUST 2026  Case', 'Report Month:')).toEqual({ year: 2026, month: 8 });
    expect(parseReportMonth('no label here', 'Report Month:')).toBeUndefined();
    expect(lastDayOf({ year: 2028, month: 2 })).toEqual({ year: 2028, month: 2, day: 29 });
  });
});

describe('the homography underneath the alignment', () => {
  const square: Point[] = [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 0, y: 1 },
  ];

  it('recovers a perspective warp from four points', () => {
    const warped: Point[] = [
      { x: 0.1, y: 0.05 },
      { x: 0.92, y: 0.1 },
      { x: 0.85, y: 0.95 },
      { x: 0.05, y: 0.9 },
    ];
    const h = fitHomography(square, warped);
    expect(h).toBeDefined();
    square.forEach((p, i) => {
      const q = applyHomography(h!, p);
      expect(q.x).toBeCloseTo(warped[i]!.x, 6);
      expect(q.y).toBeCloseTo(warped[i]!.y, 6);
    });
  });

  it('ignores a wrong match when the others agree', () => {
    const from: Point[] = [];
    for (let i = 0; i < 12; i++) from.push({ x: (i % 4) / 3, y: Math.floor(i / 4) / 2 });
    const to = from.map((p) => ({ x: 0.05 + p.x * 0.9, y: 0.02 + p.y * 0.95 }));
    // One line matched to the wrong place on the page, as a repeated heading would be.
    to[5] = { x: 0.9, y: 0.1 };
    const pairs = from.map((p, i) => ({ from: p, to: to[i]!, group: i }));
    const fit = ransacHomography(pairs, { iterations: 200, threshold: 0.01, minGroups: 6, seed: 7 });
    expect(fit).toBeDefined();
    expect(fit!.inliers).not.toContain(5);
    const q = applyHomography(fit!.h, from[5]!);
    expect(q.x).toBeCloseTo(0.05 + from[5]!.x * 0.9, 3);
  });
});
